export const ERROR_CODES = {

  MISSING_FIELDS: "MISSING_FIELDS",

  UNAUTHORIZED: "UNAUTHORIZED",

  FORBIDDEN: "FORBIDDEN",

  NOT_FOUND: "NOT_FOUND",

  INVALID_FILE: "INVALID_FILE",

  DATABASE_ERROR: "DATABASE_ERROR",

  COMMENT_BLOCKED: "COMMENT_BLOCKED",

  ALREADY_EXISTS: "ALREADY_EXISTS",

  UNKNOWN_ERROR: "UNKNOWN_ERROR"

} as const;
